[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"

[build]
  command = "pnpx nx export $PROJECT_NAME"

[build.environment]
  NETLIFY_USE_YARN="false"
  NPM_FLAGS="--version"
  NODE_VERSION = "16"
