[[plugins]]
package = "./tools/plugins/netlify/stop-build"

[build]
  command = "npx pnpm install --store-dir=.pnpm --frozen-lockfile && npx pnpm export $PROJECT_NAME"

[build.environment]
  NETLIFY_USE_YARN="false"
  NPM_FLAGS="--version"
  NODE_VERSION = "18"
