[[plugins]]
package = "./tools/plugins/netlify/stop-build"

[[plugins]]
package = "/netlify-plugin-cache"

  [plugins.inputs]
  paths = [".pnpm"]

[[build]]
  command = "npx pnpm install --store-dir=.pnpm --frozen-lockfile && npx pnpm export $PROJECT_NAME"

[build.environment]
  NPM_FLAGS="--version"
  NODE_VERSION = "18"